var PUZZLE_STAGES = [
    {
        board: { cols: 5, rows: 5 },
        moves: 2,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 0, y: 0, v: 3, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'east' }
        ]
    },
    {
        board: { cols: 5, rows: 7 },
        moves: 2,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 3, y: 2, v: 3, rot: 0 }
        ],
        solution: [
            { x: 3, y: 2, dir: 'west', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 5 },
        moves: 2,
        walls: [],
        dice: [
            { x: 0, y: 1, v: 4, rot: 0 },
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 0, y: 2, v: 4, rot: 0 },
            { x: 0, y: 0, v: 5, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'east' }
        ]
    },
    {
        board: { cols: 5, rows: 7 },
        moves: 2,
        walls: [],
        dice: [
            { x: 2, y: 2, v: 2, rot: 0 },
            { x: 3, y: 2, v: 2, rot: 0 },
            { x: 1, y: 1, v: 2, rot: 0 }
        ],
        solution: [
            { x: 1, y: 1, dir: 'south' }
        ]
    },
    {
        board: { cols: 5, rows: 5 },
        moves: 2,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 2, y: 1, v: 4, rot: 0 },
            { x: 3, y: 1, v: 4, rot: 0 },
            { x: 3, y: 2, v: 4, rot: 0 }
        ],
        solution: [
            { x: 3, y: 2, dir: 'west', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 7 },
        moves: 3,
        walls: [],
        dice: [
            { x: 1, y: 2, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 3, y: 2, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 1, y: 4, v: 2, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 2, y: 5, v: 2, rot: 0 }
        ],
        solution: [
            { x: 2, y: 1, dir: 'east' },
            { x: 2, y: 5, dir: 'north', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 5 },
        moves: 3,
        walls: [],
        dice: [
            { x: 0, y: 1, v: 4, rot: 0 },
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 0, y: 2, v: 4, rot: 0 },
            { x: 0, y: 0, v: 5, rot: 0 },
            { x: 3, y: 1, v: 5, rot: 0 },
            { x: 4, y: 1, v: 5, rot: 0 },
            { x: 3, y: 2, v: 5, rot: 0 },
            { x: 4, y: 2, v: 5, rot: 0 },
            { x: 4, y: 3, v: 4, rot: 1 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'east' },
            { x: 4, y: 3, dir: 'west' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 4,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 0, v: 3, rot: 0 },
            { x: 5, y: 1, v: 6, rot: 0 },
            { x: 4, y: 2, v: 6, rot: 0 },
            { x: 5, y: 2, v: 6, rot: 0 },
            { x: 6, y: 2, v: 6, rot: 0 },
            { x: 5, y: 3, v: 6, rot: 0 },
            { x: 4, y: 3, v: 1, rot: 0 },
            { x: 6, y: 4, v: 5, rot: 1 },
            { x: 1, y: 4, v: 2, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 2, y: 5, v: 2, rot: 0 }
        ],
        solution: [
            { x: 2, y: 0, dir: 'east' },
            { x: 6, y: 4, dir: 'west' },
            { x: 2, y: 5, dir: 'north', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 7 },
        moves: 4,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 0, v: 3, rot: 0 },
            { x: 3, y: 4, v: 4, rot: 0 },
            { x: 4, y: 4, v: 4, rot: 0 },
            { x: 3, y: 5, v: 4, rot: 0 },
            { x: 4, y: 5, v: 4, rot: 0 },
            { x: 0, y: 3, v: 2, rot: 0 },
            { x: 2, y: 3, v: 2, rot: 0 },
            { x: 1, y: 4, v: 2, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 0, y: 6, v: 3, rot: 0 },
            { x: 1, y: 5, v: 3, rot: 0 }
        ],
        solution: [
            { x: 2, y: 0, dir: 'east' },
            { x: 1, y: 4, dir: 'north', type: 'slide' },
            { x: 1, y: 5, dir: 'west', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 5 },
        moves: 4,
        walls: [],
        dice: [
            { x: 0, y: 0, v: 5, rot: 0 },
            { x: 0, y: 1, v: 5, rot: 0 },
            { x: 1, y: 1, v: 5, rot: 0 },
            { x: 2, y: 1, v: 5, rot: 0 },
            { x: 0, y: 2, v: 5, rot: 0 },
            { x: 1, y: 0, v: 5, rot: 1 },
            { x: 3, y: 2, v: 4, rot: 0 },
            { x: 4, y: 2, v: 4, rot: 0 },
            { x: 4, y: 3, v: 4, rot: 0 },
            { x: 2, y: 3, v: 5, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 2, y: 3, dir: 'east' },
            { x: 1, y: 3, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 7 },
        moves: 5,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 0, v: 3, rot: 0 },
            { x: 0, y: 5, v: 4, rot: 0 },
            { x: 1, y: 5, v: 4, rot: 0 },
            { x: 0, y: 6, v: 4, rot: 0 },
            { x: 1, y: 6, v: 4, rot: 0 },
            { x: 3, y: 4, v: 3, rot: 0 },
            { x: 4, y: 4, v: 3, rot: 0 },
            { x: 2, y: 5, v: 3, rot: 0 },
            { x: 0, y: 3, v: 2, rot: 0 },
            { x: 2, y: 3, v: 2, rot: 0 },
            { x: 1, y: 4, v: 2, rot: 0 },
            { x: 3, y: 2, v: 4, rot: 0 },
            { x: 4, y: 2, v: 4, rot: 0 },
            { x: 3, y: 3, v: 4, rot: 0 },
            { x: 1, y: 2, v: 5, rot: 0 }
        ],
        solution: [
            { x: 2, y: 0, dir: 'east' },
            { x: 2, y: 5, dir: 'north', type: 'slide' },
            { x: 1, y: 4, dir: 'north', type: 'slide' },
            { x: 1, y: 2, dir: 'east' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 5,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 1, y: 0, v: 3, rot: 0 },
            { x: 5, y: 1, v: 6, rot: 0 },
            { x: 4, y: 2, v: 6, rot: 0 },
            { x: 5, y: 2, v: 6, rot: 0 },
            { x: 6, y: 2, v: 6, rot: 0 },
            { x: 5, y: 3, v: 6, rot: 0 },
            { x: 4, y: 3, v: 1, rot: 0 },
            { x: 6, y: 4, v: 5, rot: 1 },
            { x: 1, y: 4, v: 3, rot: 0 },
            { x: 1, y: 6, v: 3, rot: 0 },
            { x: 2, y: 5, v: 3, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 3, y: 6, v: 2, rot: 0 },
            { x: 4, y: 5, v: 2, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 6, y: 4, dir: 'west' },
            { x: 2, y: 5, dir: 'west', type: 'slide' },
            { x: 4, y: 5, dir: 'west', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 7 },
        moves: 5,
        walls: [],
        dice: [
            { x: 3, y: 2, v: 4, rot: 0 },
            { x: 4, y: 2, v: 4, rot: 0 },
            { x: 3, y: 3, v: 4, rot: 0 },
            { x: 4, y: 3, v: 4, rot: 0 },
            { x: 1, y: 2, v: 4, rot: 2 },
            { x: 3, y: 5, v: 4, rot: 0 },
            { x: 4, y: 5, v: 4, rot: 0 },
            { x: 4, y: 6, v: 4, rot: 0 },
            { x: 2, y: 4, v: 4, rot: 0 },
            { x: 0, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 1, y: 0, v: 3, rot: 0 },
            { x: 0, y: 6, v: 2, rot: 0 },
            { x: 2, y: 6, v: 2, rot: 0 },
            { x: 1, y: 5, v: 2, rot: 0 }
        ],
        solution: [
            { x: 1, y: 2, dir: 'east' },
            { x: 2, y: 4, dir: 'east', type: 'slide' },
            { x: 1, y: 0, dir: 'south', type: 'slide' },
            { x: 1, y: 5, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 6,
        walls: [],
        dice: [
            { x: 2, y: 0, v: 5, rot: 0 },
            { x: 1, y: 1, v: 5, rot: 0 },
            { x: 2, y: 1, v: 5, rot: 0 },
            { x: 3, y: 1, v: 5, rot: 0 },
            { x: 2, y: 2, v: 5, rot: 0 },
            { x: 3, y: 3, v: 5, rot: 0 },
            { x: 1, y: 4, v: 4, rot: 0 },
            { x: 2, y: 4, v: 4, rot: 0 },
            { x: 2, y: 5, v: 4, rot: 0 },
            { x: 0, y: 3, v: 5, rot: 0 },
            { x: 5, y: 4, v: 4, rot: 0 },
            { x: 6, y: 4, v: 4, rot: 0 },
            { x: 6, y: 5, v: 4, rot: 0 },
            { x: 4, y: 3, v: 5, rot: 0 },
            { x: 0, y: 6, v: 3, rot: 0 },
            { x: 2, y: 6, v: 3, rot: 0 },
            { x: 1, y: 5, v: 3, rot: 0 },
            { x: 4, y: 6, v: 2, rot: 0 },
            { x: 6, y: 6, v: 2, rot: 0 },
            { x: 5, y: 5, v: 2, rot: 0 }
        ],
        solution: [
            { x: 3, y: 3, dir: 'north' },
            { x: 0, y: 3, dir: 'east' },
            { x: 4, y: 3, dir: 'east' },
            { x: 1, y: 5, dir: 'south', type: 'slide' },
            { x: 5, y: 5, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 7 },
        moves: 5,
        walls: [],
        dice: [
            { x: 0, y: 1, v: 3, rot: 0 },
            { x: 0, y: 2, v: 3, rot: 0 },
            { x: 1, y: 3, v: 2, rot: 0 },
            { x: 3, y: 0, v: 3, rot: 0 },
            { x: 4, y: 0, v: 3, rot: 0 },
            { x: 3, y: 2, v: 3, rot: 0 },
            { x: 1, y: 4, v: 4, rot: 0 },
            { x: 2, y: 4, v: 4, rot: 0 },
            { x: 1, y: 5, v: 4, rot: 0 },
            { x: 2, y: 2, v: 4, rot: 0 },
            { x: 2, y: 6, v: 2, rot: 0 },
            { x: 4, y: 6, v: 2, rot: 0 },
            { x: 3, y: 5, v: 2, rot: 0 },
            { x: 2, y: 5, v: 1, rot: 0 }
        ],
        solution: [
            { x: 1, y: 3, dir: 'west' },
            { x: 3, y: 2, dir: 'north', type: 'slide' },
            { x: 2, y: 2, dir: 'south', type: 'slide' },
            { x: 3, y: 5, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 6,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 6, rot: 0 },
            { x: 2, y: 1, v: 6, rot: 0 },
            { x: 3, y: 1, v: 6, rot: 0 },
            { x: 1, y: 2, v: 6, rot: 0 },
            { x: 2, y: 2, v: 6, rot: 0 },
            { x: 3, y: 2, v: 6, rot: 0 },
            { x: 4, y: 3, v: 3, rot: 0 },
            { x: 1, y: 4, v: 4, rot: 0 },
            { x: 2, y: 4, v: 4, rot: 0 },
            { x: 2, y: 5, v: 4, rot: 0 },
            { x: 0, y: 3, v: 5, rot: 0 },
            { x: 5, y: 4, v: 4, rot: 0 },
            { x: 6, y: 4, v: 4, rot: 0 },
            { x: 6, y: 5, v: 4, rot: 0 },
            { x: 5, y: 2, v: 5, rot: 1 },
            { x: 0, y: 6, v: 3, rot: 0 },
            { x: 2, y: 6, v: 3, rot: 0 },
            { x: 1, y: 5, v: 3, rot: 0 },
            { x: 4, y: 6, v: 2, rot: 0 },
            { x: 6, y: 6, v: 2, rot: 0 },
            { x: 5, y: 5, v: 2, rot: 0 },
            { x: 4, y: 5, v: 1, rot: 0 }
        ],
        solution: [
            { x: 4, y: 3, dir: 'west' },
            { x: 0, y: 3, dir: 'east' },
            { x: 5, y: 2, dir: 'south' },
            { x: 1, y: 5, dir: 'south', type: 'slide' },
            { x: 5, y: 5, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 7 },
        moves: 6,
        walls: [],
        dice: [
            { x: 0, y: 0, v: 6, rot: 0 },
            { x: 1, y: 0, v: 6, rot: 0 },
            { x: 2, y: 0, v: 6, rot: 0 },
            { x: 1, y: 1, v: 6, rot: 0 },
            { x: 1, y: 2, v: 6, rot: 0 },
            { x: 1, y: 3, v: 6, rot: 0 },
            { x: 3, y: 0, v: 4, rot: 0 },
            { x: 4, y: 0, v: 4, rot: 0 },
            { x: 3, y: 1, v: 4, rot: 0 },
            { x: 4, y: 1, v: 4, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 3, y: 2, v: 3, rot: 0 },
            { x: 4, y: 2, v: 3, rot: 0 },
            { x: 0, y: 3, v: 2, rot: 0 },
            { x: 1, y: 4, v: 3, rot: 3 },
            { x: 2, y: 4, v: 6, rot: 0 },
            { x: 3, y: 4, v: 6, rot: 0 },
            { x: 4, y: 4, v: 6, rot: 0 },
            { x: 4, y: 5, v: 6, rot: 0 },
            { x: 4, y: 6, v: 6, rot: 0 },
            { x: 1, y: 6, v: 6, rot: 0 },
            { x: 0, y: 5, v: 3, rot: 0 },
            { x: 0, y: 6, v: 3, rot: 0 },
            { x: 3, y: 5, v: 3, rot: 0 }
        ],
        solution: [
            { x: 1, y: 4, dir: 'west' },
            { x: 1, y: 6, dir: 'east', type: 'slide' },
            { x: 2, y: 6, dir: 'east', type: 'slide' },
            { x: 3, y: 5, dir: 'west', type: 'slide' },
            { x: 2, y: 5, dir: 'west', type: 'slide' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 6,
        walls: [],
        dice: [
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 4, y: 1, v: 3, rot: 0 },
            { x: 2, y: 0, v: 3, rot: 0 },
            { x: 0, y: 4, v: 4, rot: 0 },
            { x: 1, y: 4, v: 4, rot: 0 },
            { x: 0, y: 5, v: 4, rot: 0 },
            { x: 2, y: 5, v: 4, rot: 0 },
            { x: 5, y: 4, v: 4, rot: 0 },
            { x: 6, y: 4, v: 4, rot: 0 },
            { x: 6, y: 5, v: 4, rot: 0 },
            { x: 4, y: 5, v: 4, rot: 0 },
            { x: 2, y: 6, v: 3, rot: 0 },
            { x: 4, y: 6, v: 3, rot: 0 },
            { x: 3, y: 5, v: 3, rot: 0 },
            { x: 2, y: 2, v: 2, rot: 0 },
            { x: 2, y: 4, v: 2, rot: 0 },
            { x: 1, y: 3, v: 2, rot: 0 }
        ],
        solution: [
            { x: 2, y: 0, dir: 'east' },
            { x: 2, y: 5, dir: 'west', type: 'slide' },
            { x: 4, y: 5, dir: 'east', type: 'slide' },
            { x: 3, y: 5, dir: 'south', type: 'slide' },
            { x: 1, y: 3, dir: 'east', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 7 },
        moves: 7,
        walls: [],
        dice: [
            { x: 1, y: 2, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 3, y: 2, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 0, y: 1, v: 5, rot: 0 },
            { x: 1, y: 1, v: 5, rot: 0 },
            { x: 0, y: 2, v: 5, rot: 0 },
            { x: 0, y: 3, v: 5, rot: 0 },
            { x: 2, y: 0, v: 4, rot: 1 },
            { x: 3, y: 4, v: 4, rot: 0 },
            { x: 4, y: 4, v: 4, rot: 0 },
            { x: 4, y: 5, v: 4, rot: 0 },
            { x: 2, y: 3, v: 5, rot: 0 },
            { x: 0, y: 6, v: 3, rot: 0 },
            { x: 2, y: 6, v: 3, rot: 0 },
            { x: 1, y: 5, v: 3, rot: 0 },
            { x: 0, y: 4, v: 2, rot: 0 },
            { x: 2, y: 4, v: 2, rot: 0 },
            { x: 1, y: 3, v: 2, rot: 0 }
        ],
        solution: [
            { x: 2, y: 1, dir: 'east' },
            { x: 2, y: 0, dir: 'west' },
            { x: 2, y: 3, dir: 'east' },
            { x: 1, y: 5, dir: 'south', type: 'slide' },
            { x: 1, y: 3, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 7,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 5, rot: 0 },
            { x: 2, y: 1, v: 5, rot: 0 },
            { x: 3, y: 1, v: 5, rot: 0 },
            { x: 4, y: 1, v: 5, rot: 0 },
            { x: 1, y: 2, v: 5, rot: 0 },
            { x: 3, y: 2, v: 5, rot: 0 },
            { x: 2, y: 0, v: 5, rot: 1 },
            { x: 0, y: 3, v: 4, rot: 0 },
            { x: 1, y: 3, v: 4, rot: 0 },
            { x: 0, y: 4, v: 4, rot: 0 },
            { x: 1, y: 5, v: 5, rot: 3 },
            { x: 5, y: 1, v: 3, rot: 0 },
            { x: 6, y: 1, v: 3, rot: 0 },
            { x: 5, y: 3, v: 3, rot: 0 },
            { x: 4, y: 4, v: 2, rot: 0 },
            { x: 6, y: 4, v: 2, rot: 0 },
            { x: 5, y: 5, v: 2, rot: 0 },
            { x: 1, y: 6, v: 2, rot: 0 },
            { x: 3, y: 6, v: 2, rot: 0 },
            { x: 2, y: 5, v: 2, rot: 0 },
            { x: 2, y: 3, v: 1, rot: 0 },
            { x: 0, y: 6, v: 1, rot: 0 }
        ],
        solution: [
            { x: 2, y: 0, dir: 'east' },
            { x: 1, y: 5, dir: 'north' },
            { x: 5, y: 3, dir: 'north', type: 'slide' },
            { x: 5, y: 5, dir: 'north', type: 'slide' },
            { x: 2, y: 5, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 7 },
        moves: 5,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 1, y: 0, v: 3, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 0, y: 6, v: 2, rot: 0 },
            { x: 2, y: 6, v: 2, rot: 0 },
            { x: 1, y: 5, v: 2, rot: 0 },
            { x: 4, y: 4, v: 3, rot: 0 },
            { x: 4, y: 6, v: 3, rot: 0 },
            { x: 3, y: 5, v: 3, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 1, y: 5, dir: 'south', type: 'slide' },
            { x: 3, y: 5, dir: 'east', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 8,
        walls: [],
        dice: [
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 4, y: 1, v: 3, rot: 0 },
            { x: 3, y: 2, v: 3, rot: 0 },
            { x: 2, y: 0, v: 3, rot: 0 },
            { x: 6, y: 3, v: 4, rot: 0 },
            { x: 7, y: 3, v: 4, rot: 0 },
            { x: 7, y: 4, v: 4, rot: 0 },
            { x: 5, y: 2, v: 5, rot: 0 },
            { x: 0, y: 3, v: 3, rot: 0 },
            { x: 2, y: 3, v: 3, rot: 0 },
            { x: 1, y: 4, v: 3, rot: 0 },
            { x: 8, y: 0, v: 2, rot: 0 },
            { x: 8, y: 2, v: 2, rot: 0 },
            { x: 7, y: 1, v: 2, rot: 0 },
            { x: 5, y: 0, v: 3, rot: 0 },
            { x: 7, y: 0, v: 3, rot: 0 },
            { x: 6, y: 1, v: 3, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 5, y: 4, v: 2, rot: 0 },
            { x: 4, y: 3, v: 2, rot: 0 },
            { x: 2, y: 4, v: 1, rot: 0 }
        ],
        solution: [
            { x: 2, y: 0, dir: 'east' },
            { x: 5, y: 2, dir: 'east' },
            { x: 1, y: 4, dir: 'north', type: 'slide' },
            { x: 7, y: 1, dir: 'east', type: 'slide' },
            { x: 6, y: 1, dir: 'north', type: 'slide' },
            { x: 4, y: 3, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 8,
        walls: [],
        dice: [
            { x: 2, y: 1, v: 2, rot: 0 },
            { x: 3, y: 1, v: 2, rot: 0 },
            { x: 4, y: 1, v: 2, rot: 0 },
            { x: 6, y: 1, v: 2, rot: 1 },
            { x: 5, y: 4, v: 4, rot: 0 },
            { x: 6, y: 4, v: 4, rot: 0 },
            { x: 6, y: 5, v: 4, rot: 0 },
            { x: 4, y: 3, v: 5, rot: 0 },
            { x: 0, y: 6, v: 3, rot: 0 },
            { x: 2, y: 6, v: 3, rot: 0 },
            { x: 1, y: 5, v: 3, rot: 0 },
            { x: 2, y: 4, v: 2, rot: 0 },
            { x: 4, y: 4, v: 2, rot: 0 },
            { x: 3, y: 3, v: 2, rot: 0 },
            { x: 4, y: 6, v: 2, rot: 0 },
            { x: 6, y: 6, v: 2, rot: 0 },
            { x: 5, y: 5, v: 2, rot: 0 },
            { x: 0, y: 5, v: 1, rot: 0 }
        ],
        solution: [
            { x: 6, y: 1, dir: 'west' },
            { x: 4, y: 3, dir: 'east' },
            { x: 1, y: 5, dir: 'south', type: 'slide' },
            { x: 3, y: 3, dir: 'south', type: 'slide' },
            { x: 5, y: 5, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 8,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 1, y: 0, v: 3, rot: 0 },
            { x: 5, y: 1, v: 4, rot: 0 },
            { x: 6, y: 1, v: 4, rot: 0 },
            { x: 6, y: 2, v: 4, rot: 0 },
            { x: 4, y: 0, v: 5, rot: 0 },
            { x: 8, y: 0, v: 3, rot: 0 },
            { x: 8, y: 2, v: 3, rot: 0 },
            { x: 7, y: 1, v: 3, rot: 0 },
            { x: 1, y: 4, v: 2, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 2, y: 3, v: 2, rot: 0 },
            { x: 5, y: 4, v: 3, rot: 0 },
            { x: 7, y: 4, v: 3, rot: 0 },
            { x: 6, y: 3, v: 3, rot: 0 },
            { x: 4, y: 1, v: 2, rot: 0 },
            { x: 4, y: 3, v: 2, rot: 0 },
            { x: 5, y: 2, v: 2, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 4, y: 0, dir: 'east' },
            { x: 7, y: 1, dir: 'east', type: 'slide' },
            { x: 2, y: 3, dir: 'south', type: 'slide' },
            { x: 6, y: 3, dir: 'south', type: 'slide' },
            { x: 5, y: 2, dir: 'west', type: 'slide' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 8,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 5, rot: 0 },
            { x: 2, y: 1, v: 5, rot: 0 },
            { x: 1, y: 2, v: 5, rot: 0 },
            { x: 2, y: 2, v: 5, rot: 0 },
            { x: 0, y: 0, v: 3, rot: 0 },
            { x: 4, y: 2, v: 4, rot: 0 },
            { x: 5, y: 2, v: 4, rot: 0 },
            { x: 4, y: 3, v: 4, rot: 0 },
            { x: 5, y: 4, v: 6, rot: 3 },
            { x: 6, y: 4, v: 3, rot: 0 },
            { x: 6, y: 6, v: 3, rot: 0 },
            { x: 5, y: 5, v: 2, rot: 2 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 0, y: 6, v: 2, rot: 0 },
            { x: 2, y: 6, v: 2, rot: 0 },
            { x: 1, y: 5, v: 2, rot: 0 },
            { x: 4, y: 1, v: 2, rot: 0 },
            { x: 6, y: 1, v: 2, rot: 0 },
            { x: 5, y: 0, v: 2, rot: 0 },
            { x: 4, y: 4, v: 3, rot: 0 },
            { x: 4, y: 6, v: 3, rot: 0 },
            { x: 3, y: 5, v: 3, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'south' },
            { x: 5, y: 4, dir: 'north' },
            { x: 5, y: 5, dir: 'east' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 1, y: 5, dir: 'south', type: 'slide' },
            { x: 5, y: 0, dir: 'south', type: 'slide' },
            { x: 3, y: 5, dir: 'east', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 9,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 2, y: 1, v: 4, rot: 0 },
            { x: 3, y: 1, v: 4, rot: 0 },
            { x: 2, y: 2, v: 4, rot: 0 },
            { x: 1, y: 0, v: 4, rot: 2 },
            { x: 6, y: 3, v: 3, rot: 0 },
            { x: 7, y: 3, v: 3, rot: 0 },
            { x: 4, y: 3, v: 3, rot: 0 },
            { x: 1, y: 3, v: 4, rot: 0 },
            { x: 1, y: 4, v: 4, rot: 0 },
            { x: 2, y: 4, v: 4, rot: 0 },
            { x: 3, y: 3, v: 4, rot: 0 },
            { x: 5, y: 1, v: 3, rot: 0 },
            { x: 7, y: 1, v: 3, rot: 0 },
            { x: 6, y: 0, v: 3, rot: 0 },
            { x: 3, y: 0, v: 2, rot: 0 },
            { x: 5, y: 0, v: 2, rot: 0 },
            { x: 4, y: 1, v: 2, rot: 0 },
            { x: 8, y: 1, v: 1, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 4, y: 3, dir: 'east', type: 'slide' },
            { x: 3, y: 3, dir: 'west', type: 'slide' },
            { x: 6, y: 0, dir: 'south', type: 'slide' },
            { x: 4, y: 1, dir: 'north', type: 'slide' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 9,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 6, rot: 0 },
            { x: 2, y: 1, v: 6, rot: 0 },
            { x: 3, y: 1, v: 6, rot: 0 },
            { x: 1, y: 2, v: 6, rot: 0 },
            { x: 2, y: 2, v: 6, rot: 0 },
            { x: 3, y: 2, v: 6, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 5, y: 3, v: 4, rot: 0 },
            { x: 6, y: 3, v: 4, rot: 0 },
            { x: 6, y: 4, v: 4, rot: 0 },
            { x: 4, y: 2, v: 5, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 4, y: 4, v: 3, rot: 0 },
            { x: 3, y: 3, v: 3, rot: 0 },
            { x: 0, y: 6, v: 2, rot: 0 },
            { x: 2, y: 6, v: 2, rot: 0 },
            { x: 1, y: 5, v: 2, rot: 0 },
            { x: 4, y: 0, v: 3, rot: 0 },
            { x: 6, y: 0, v: 3, rot: 0 },
            { x: 5, y: 1, v: 3, rot: 0 },
            { x: 4, y: 6, v: 2, rot: 0 },
            { x: 6, y: 6, v: 2, rot: 0 },
            { x: 5, y: 5, v: 2, rot: 0 },
            { x: 0, y: 5, v: 1, rot: 0 }
        ],
        solution: [
            { x: 1, y: 3, dir: 'east' },
            { x: 4, y: 2, dir: 'east' },
            { x: 3, y: 3, dir: 'south', type: 'slide' },
            { x: 1, y: 5, dir: 'south', type: 'slide' },
            { x: 5, y: 1, dir: 'north', type: 'slide' },
            { x: 5, y: 5, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 9,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 1, y: 0, v: 3, rot: 0 },
            { x: 5, y: 1, v: 4, rot: 0 },
            { x: 6, y: 1, v: 4, rot: 0 },
            { x: 6, y: 2, v: 4, rot: 0 },
            { x: 4, y: 0, v: 5, rot: 0 },
            { x: 8, y: 0, v: 3, rot: 0 },
            { x: 8, y: 2, v: 3, rot: 0 },
            { x: 7, y: 1, v: 3, rot: 0 },
            { x: 0, y: 4, v: 2, rot: 0 },
            { x: 2, y: 4, v: 2, rot: 0 },
            { x: 1, y: 3, v: 2, rot: 0 },
            { x: 5, y: 4, v: 3, rot: 0 },
            { x: 7, y: 4, v: 3, rot: 0 },
            { x: 6, y: 3, v: 3, rot: 0 },
            { x: 3, y: 3, v: 2, rot: 0 },
            { x: 5, y: 3, v: 2, rot: 0 },
            { x: 4, y: 2, v: 2, rot: 0 },
            { x: 4, y: 4, v: 1, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 4, y: 0, dir: 'east' },
            { x: 7, y: 1, dir: 'east', type: 'slide' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 6, y: 3, dir: 'south', type: 'slide' },
            { x: 4, y: 2, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 7,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 2, y: 1, v: 4, rot: 0 },
            { x: 1, y: 2, v: 4, rot: 0 },
            { x: 2, y: 2, v: 4, rot: 0 },
            { x: 3, y: 1, v: 4, rot: 3 },
            { x: 4, y: 2, v: 6, rot: 0 },
            { x: 5, y: 1, v: 6, rot: 0 },
            { x: 5, y: 2, v: 6, rot: 0 },
            { x: 6, y: 2, v: 6, rot: 0 },
            { x: 5, y: 3, v: 6, rot: 0 },
            { x: 6, y: 4, v: 5, rot: 1 },
            { x: 0, y: 5, v: 3, rot: 0 },
            { x: 2, y: 5, v: 3, rot: 0 },
            { x: 1, y: 4, v: 3, rot: 0 },
            { x: 4, y: 6, v: 2, rot: 0 },
            { x: 6, y: 6, v: 2, rot: 0 },
            { x: 5, y: 5, v: 2, rot: 0 },
            { x: 3, y: 4, v: 3, rot: 0 },
            { x: 3, y: 6, v: 3, rot: 0 },
            { x: 4, y: 5, v: 3, rot: 0 },
            { x: 1, y: 3, v: 2, rot: 0 },
            { x: 3, y: 3, v: 2, rot: 0 },
            { x: 2, y: 4, v: 2, rot: 0 }
        ],
        solution: [
            { x: 3, y: 1, dir: 'south' },
            { x: 6, y: 4, dir: 'west' },
            { x: 1, y: 4, dir: 'south', type: 'slide' },
            { x: 5, y: 5, dir: 'south', type: 'slide' },
            { x: 4, y: 5, dir: 'west', type: 'slide' },
            { x: 2, y: 4, dir: 'north', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 10,
        walls: [],
        dice: [
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 2, y: 1, v: 4, rot: 0 },
            { x: 1, y: 2, v: 4, rot: 0 },
            { x: 2, y: 2, v: 4, rot: 0 },
            { x: 0, y: 0, v: 4, rot: 3 },
            { x: 6, y: 0, v: 5, rot: 0 },
            { x: 7, y: 0, v: 5, rot: 0 },
            { x: 6, y: 1, v: 5, rot: 0 },
            { x: 7, y: 1, v: 5, rot: 0 },
            { x: 4, y: 0, v: 4, rot: 3 },
            { x: 8, y: 3, v: 3, rot: 0 },
            { x: 8, y: 4, v: 3, rot: 0 },
            { x: 6, y: 4, v: 3, rot: 0 },
            { x: 0, y: 4, v: 2, rot: 0 },
            { x: 2, y: 4, v: 2, rot: 0 },
            { x: 1, y: 3, v: 2, rot: 0 },
            { x: 4, y: 3, v: 3, rot: 0 },
            { x: 6, y: 3, v: 3, rot: 0 },
            { x: 5, y: 2, v: 3, rot: 0 },
            { x: 3, y: 1, v: 2, rot: 0 },
            { x: 3, y: 3, v: 2, rot: 0 },
            { x: 4, y: 2, v: 2, rot: 0 },
            { x: 6, y: 2, v: 2, rot: 0 },
            { x: 8, y: 2, v: 2, rot: 0 },
            { x: 7, y: 3, v: 2, rot: 0 },
            { x: 8, y: 1, v: 1, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'south' },
            { x: 4, y: 0, dir: 'east' },
            { x: 6, y: 4, dir: 'east', type: 'slide' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 5, y: 2, dir: 'south', type: 'slide' },
            { x: 4, y: 2, dir: 'west', type: 'slide' },
            { x: 7, y: 3, dir: 'north', type: 'slide' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 7,
        walls: [{ x: 0, y: 0 }, { x: 4, y: 1 }],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 1, y: 0, v: 3, rot: 0 },
            { x: 4, y: 2, v: 4, rot: 0 },
            { x: 5, y: 2, v: 4, rot: 0 },
            { x: 4, y: 3, v: 4, rot: 0 },
            { x: 5, y: 3, v: 4, rot: 0 },
            { x: 3, y: 3, v: 4, rot: 1 },
            { x: 0, y: 5, v: 3, rot: 0 },
            { x: 2, y: 5, v: 3, rot: 0 },
            { x: 1, y: 4, v: 3, rot: 0 },
            { x: 4, y: 6, v: 2, rot: 0 },
            { x: 6, y: 6, v: 2, rot: 0 },
            { x: 5, y: 5, v: 2, rot: 0 },
            { x: 3, y: 4, v: 3, rot: 0 },
            { x: 5, y: 4, v: 3, rot: 0 },
            { x: 4, y: 5, v: 3, rot: 0 },
            { x: 0, y: 3, v: 2, rot: 0 },
            { x: 2, y: 3, v: 2, rot: 0 },
            { x: 1, y: 2, v: 2, rot: 0 },
            { x: 4, y: 0, v: 3, rot: 0 },
            { x: 6, y: 0, v: 3, rot: 0 },
            { x: 5, y: 1, v: 3, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 1, y: 4, dir: 'south', type: 'slide' },
            { x: 5, y: 5, dir: 'south', type: 'slide' },
            { x: 4, y: 5, dir: 'north', type: 'slide' },
            { x: 1, y: 2, dir: 'south', type: 'slide' },
            { x: 5, y: 1, dir: 'north', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 7,
        walls: [{ x: 4, y: 1 }, { x: 4, y: 3 }],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 1, y: 0, v: 3, rot: 0 },
            { x: 6, y: 0, v: 4, rot: 0 },
            { x: 7, y: 0, v: 4, rot: 0 },
            { x: 6, y: 1, v: 4, rot: 0 },
            { x: 7, y: 1, v: 4, rot: 0 },
            { x: 8, y: 1, v: 4, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 6, y: 4, v: 2, rot: 0 },
            { x: 8, y: 4, v: 2, rot: 0 },
            { x: 7, y: 3, v: 2, rot: 0 },
            { x: 4, y: 2, v: 3, rot: 0 },
            { x: 6, y: 2, v: 3, rot: 0 },
            { x: 5, y: 3, v: 3, rot: 0 },
            { x: 0, y: 1, v: 2, rot: 0 },
            { x: 0, y: 3, v: 2, rot: 0 },
            { x: 1, y: 2, v: 2, rot: 0 },
            { x: 0, y: 0, v: 1, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 3, dir: 'south', type: 'slide' },
            { x: 5, y: 3, dir: 'north', type: 'slide' },
            { x: 1, y: 2, dir: 'west', type: 'slide' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 6,
        walls: [{ x: 3, y: 1 }, { x: 3, y: 2 }, { x: 3, y: 3 }, { x: 3, y: 4 }],
        dice: [
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 2, y: 1, v: 4, rot: 0 },
            { x: 1, y: 2, v: 4, rot: 0 },
            { x: 2, y: 2, v: 4, rot: 0 },
            { x: 0, y: 0, v: 4, rot: 3 },
            { x: 0, y: 5, v: 3, rot: 0 },
            { x: 2, y: 5, v: 3, rot: 0 },
            { x: 1, y: 4, v: 3, rot: 0 },
            { x: 4, y: 6, v: 2, rot: 0 },
            { x: 6, y: 6, v: 2, rot: 0 },
            { x: 5, y: 5, v: 2, rot: 0 },
            { x: 4, y: 5, v: 3, rot: 0 },
            { x: 6, y: 5, v: 3, rot: 0 },
            { x: 5, y: 4, v: 3, rot: 0 },
            { x: 4, y: 1, v: 2, rot: 0 },
            { x: 6, y: 1, v: 2, rot: 0 },
            { x: 5, y: 0, v: 2, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'south' },
            { x: 1, y: 4, dir: 'south', type: 'slide' },
            { x: 5, y: 5, dir: 'south', type: 'slide' },
            { x: 5, y: 4, dir: 'south', type: 'slide' },
            { x: 5, y: 0, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 7,
        walls: [{ x: 6, y: 0 }, { x: 7, y: 0 }, { x: 8, y: 0 }],
        dice: [
            { x: 1, y: 0, v: 4, rot: 0 },
            { x: 2, y: 0, v: 4, rot: 0 },
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 2, y: 1, v: 4, rot: 0 },
            { x: 0, y: 0, v: 4, rot: 3 },
            { x: 5, y: 2, v: 5, rot: 0 },
            { x: 6, y: 2, v: 5, rot: 0 },
            { x: 5, y: 3, v: 5, rot: 0 },
            { x: 6, y: 3, v: 5, rot: 0 },
            { x: 4, y: 1, v: 4, rot: 3 },
            { x: 1, y: 4, v: 3, rot: 0 },
            { x: 3, y: 4, v: 3, rot: 0 },
            { x: 2, y: 3, v: 3, rot: 0 },
            { x: 6, y: 4, v: 2, rot: 0 },
            { x: 8, y: 4, v: 2, rot: 0 },
            { x: 7, y: 3, v: 2, rot: 0 },
            { x: 8, y: 1, v: 3, rot: 0 },
            { x: 8, y: 3, v: 3, rot: 0 },
            { x: 7, y: 2, v: 3, rot: 0 },
            { x: 0, y: 2, v: 2, rot: 0 },
            { x: 2, y: 2, v: 2, rot: 0 },
            { x: 1, y: 3, v: 2, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'south' },
            { x: 4, y: 1, dir: 'east' },
            { x: 2, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 2, dir: 'east', type: 'slide' },
            { x: 1, y: 3, dir: 'north', type: 'slide' }
        ]
    },
    {
        board: { cols: 7, rows: 7 },
        moves: 6,
        walls: [{ x: 1, y: 6 }, { x: 3, y: 5 }],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 1, y: 0, v: 3, rot: 0 },
            { x: 5, y: 0, v: 4, rot: 0 },
            { x: 4, y: 1, v: 4, rot: 0 },
            { x: 5, y: 1, v: 4, rot: 0 },
            { x: 6, y: 1, v: 4, rot: 0 },
            { x: 5, y: 2, v: 4, rot: 0 },
            { x: 0, y: 5, v: 3, rot: 0 },
            { x: 2, y: 5, v: 3, rot: 0 },
            { x: 1, y: 4, v: 3, rot: 0 },
            { x: 4, y: 6, v: 2, rot: 0 },
            { x: 6, y: 6, v: 2, rot: 0 },
            { x: 5, y: 5, v: 2, rot: 0 },
            { x: 4, y: 4, v: 3, rot: 0 },
            { x: 6, y: 4, v: 3, rot: 0 },
            { x: 5, y: 3, v: 3, rot: 0 },
            { x: 0, y: 3, v: 2, rot: 0 },
            { x: 2, y: 3, v: 2, rot: 0 },
            { x: 1, y: 2, v: 2, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 1, y: 4, dir: 'south', type: 'slide' },
            { x: 5, y: 5, dir: 'south', type: 'slide' },
            { x: 5, y: 3, dir: 'south', type: 'slide' },
            { x: 1, y: 2, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 6,
        walls: [{ x: 4, y: 0 }, { x: 4, y: 1 }, { x: 4, y: 2 }, { x: 4, y: 3 }, { x: 4, y: 4 }],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 0, y: 0, v: 3, rot: 0 },
            { x: 6, y: 0, v: 4, rot: 0 },
            { x: 5, y: 1, v: 4, rot: 0 },
            { x: 6, y: 1, v: 4, rot: 0 },
            { x: 7, y: 1, v: 4, rot: 0 },
            { x: 6, y: 2, v: 4, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 6, y: 4, v: 2, rot: 0 },
            { x: 8, y: 4, v: 2, rot: 0 },
            { x: 7, y: 3, v: 2, rot: 0 },
            { x: 5, y: 2, v: 3, rot: 0 },
            { x: 5, y: 4, v: 3, rot: 0 },
            { x: 6, y: 3, v: 3, rot: 0 },
            { x: 0, y: 1, v: 2, rot: 0 },
            { x: 0, y: 3, v: 2, rot: 0 },
            { x: 1, y: 2, v: 2, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'east' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 3, dir: 'south', type: 'slide' },
            { x: 6, y: 3, dir: 'west', type: 'slide' },
            { x: 1, y: 2, dir: 'west', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 9 },
        moves: 7,
        walls: [{ x: 3, y: 0 }, { x: 3, y: 2 }],
        dice: [
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 2, y: 1, v: 4, rot: 0 },
            { x: 1, y: 2, v: 4, rot: 0 },
            { x: 2, y: 2, v: 4, rot: 0 },
            { x: 0, y: 0, v: 4, rot: 3 },
            { x: 0, y: 3, v: 3, rot: 0 },
            { x: 2, y: 3, v: 3, rot: 0 },
            { x: 1, y: 4, v: 3, rot: 0 },
            { x: 3, y: 6, v: 3, rot: 0 },
            { x: 4, y: 6, v: 3, rot: 0 },
            { x: 4, y: 8, v: 3, rot: 0 },
            { x: 4, y: 0, v: 3, rot: 0 },
            { x: 4, y: 2, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 0, y: 8, v: 2, rot: 0 },
            { x: 2, y: 8, v: 2, rot: 0 },
            { x: 1, y: 7, v: 2, rot: 0 },
            { x: 0, y: 6, v: 2, rot: 0 },
            { x: 2, y: 6, v: 2, rot: 0 },
            { x: 1, y: 5, v: 2, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'south' },
            { x: 1, y: 4, dir: 'north', type: 'slide' },
            { x: 4, y: 8, dir: 'north', type: 'slide' },
            { x: 3, y: 1, dir: 'east', type: 'slide' },
            { x: 1, y: 7, dir: 'south', type: 'slide' },
            { x: 1, y: 5, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 7,
        walls: [{ x: 8, y: 0 }, { x: 8, y: 1 }, { x: 8, y: 2 }],
        dice: [
            { x: 2, y: 0, v: 5, rot: 0 },
            { x: 1, y: 1, v: 5, rot: 0 },
            { x: 2, y: 1, v: 5, rot: 0 },
            { x: 3, y: 1, v: 5, rot: 0 },
            { x: 2, y: 2, v: 5, rot: 0 },
            { x: 3, y: 3, v: 5, rot: 0 },
            { x: 6, y: 2, v: 4, rot: 0 },
            { x: 7, y: 2, v: 4, rot: 0 },
            { x: 7, y: 3, v: 4, rot: 0 },
            { x: 5, y: 1, v: 5, rot: 0 },
            { x: 0, y: 2, v: 3, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 5, y: 4, v: 2, rot: 0 },
            { x: 7, y: 4, v: 2, rot: 0 },
            { x: 6, y: 3, v: 2, rot: 0 },
            { x: 2, y: 3, v: 3, rot: 0 },
            { x: 4, y: 3, v: 3, rot: 0 },
            { x: 3, y: 4, v: 3, rot: 0 },
            { x: 8, y: 4, v: 1, rot: 0 }
        ],
        solution: [
            { x: 3, y: 3, dir: 'north' },
            { x: 5, y: 1, dir: 'east' },
            { x: 1, y: 3, dir: 'west', type: 'slide' },
            { x: 6, y: 3, dir: 'south', type: 'slide' },
            { x: 3, y: 4, dir: 'north', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 9 },
        moves: 7,
        walls: [{ x: 0, y: 5 }, { x: 1, y: 5 }, { x: 2, y: 5 }, { x: 3, y: 5 }, { x: 4, y: 5 }],
        dice: [
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 2, y: 1, v: 4, rot: 0 },
            { x: 1, y: 2, v: 4, rot: 0 },
            { x: 2, y: 2, v: 4, rot: 0 },
            { x: 0, y: 0, v: 4, rot: 3 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 0, y: 6, v: 2, rot: 0 },
            { x: 2, y: 6, v: 2, rot: 0 },
            { x: 1, y: 7, v: 2, rot: 0 },
            { x: 3, y: 6, v: 3, rot: 0 },
            { x: 4, y: 6, v: 3, rot: 0 },
            { x: 4, y: 8, v: 3, rot: 0 },
            { x: 3, y: 2, v: 2, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 4, y: 3, v: 2, rot: 0 },
            { x: 4, y: 0, v: 3, rot: 0 },
            { x: 4, y: 2, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'south' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 1, y: 7, dir: 'north', type: 'slide' },
            { x: 4, y: 8, dir: 'north', type: 'slide' },
            { x: 4, y: 3, dir: 'west', type: 'slide' },
            { x: 3, y: 1, dir: 'east', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 8,
        walls: [{ x: 4, y: 4 }, { x: 1, y: 0 }],
        dice: [
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 2, y: 1, v: 4, rot: 0 },
            { x: 1, y: 2, v: 4, rot: 0 },
            { x: 2, y: 2, v: 4, rot: 0 },
            { x: 0, y: 0, v: 4, rot: 3 },
            { x: 5, y: 2, v: 5, rot: 0 },
            { x: 6, y: 2, v: 5, rot: 0 },
            { x: 5, y: 3, v: 5, rot: 0 },
            { x: 6, y: 3, v: 5, rot: 0 },
            { x: 4, y: 1, v: 4, rot: 3 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 6, y: 4, v: 2, rot: 0 },
            { x: 8, y: 4, v: 2, rot: 0 },
            { x: 7, y: 3, v: 2, rot: 0 },
            { x: 8, y: 0, v: 3, rot: 0 },
            { x: 8, y: 2, v: 3, rot: 0 },
            { x: 7, y: 1, v: 3, rot: 0 },
            { x: 2, y: 3, v: 2, rot: 0 },
            { x: 4, y: 3, v: 2, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 4, y: 0, v: 3, rot: 0 },
            { x: 4, y: 2, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 3, y: 0, v: 1, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'south' },
            { x: 4, y: 1, dir: 'east' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 1, dir: 'east', type: 'slide' },
            { x: 3, y: 4, dir: 'north', type: 'slide' },
            { x: 3, y: 1, dir: 'east', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 9 },
        moves: 7,
        walls: [{ x: 0, y: 8 }, { x: 1, y: 8 }],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 1, y: 0, v: 3, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 0, y: 6, v: 2, rot: 0 },
            { x: 2, y: 6, v: 2, rot: 0 },
            { x: 1, y: 7, v: 2, rot: 0 },
            { x: 3, y: 6, v: 3, rot: 0 },
            { x: 4, y: 6, v: 3, rot: 0 },
            { x: 4, y: 8, v: 3, rot: 0 },
            { x: 3, y: 2, v: 2, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 4, y: 3, v: 2, rot: 0 },
            { x: 3, y: 0, v: 1, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 1, y: 7, dir: 'north', type: 'slide' },
            { x: 4, y: 8, dir: 'north', type: 'slide' },
            { x: 4, y: 3, dir: 'west', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 7,
        walls: [{ x: 4, y: 4 }, { x: 8, y: 0 }],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 1, y: 0, v: 3, rot: 0 },
            { x: 6, y: 1, v: 4, rot: 0 },
            { x: 7, y: 1, v: 4, rot: 0 },
            { x: 6, y: 2, v: 4, rot: 0 },
            { x: 7, y: 2, v: 4, rot: 0 },
            { x: 8, y: 2, v: 4, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 6, y: 4, v: 2, rot: 0 },
            { x: 8, y: 4, v: 2, rot: 0 },
            { x: 7, y: 3, v: 2, rot: 0 },
            { x: 4, y: 3, v: 3, rot: 0 },
            { x: 6, y: 3, v: 3, rot: 0 },
            { x: 5, y: 2, v: 3, rot: 0 },
            { x: 0, y: 1, v: 2, rot: 0 },
            { x: 0, y: 3, v: 2, rot: 0 },
            { x: 1, y: 2, v: 2, rot: 0 },
            { x: 5, y: 1, v: 3, rot: 0 },
            { x: 4, y: 0, v: 3, rot: 0 },
            { x: 6, y: 0, v: 3, rot: 0 },
            { x: 0, y: 0, v: 1, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 3, dir: 'south', type: 'slide' },
            { x: 5, y: 2, dir: 'south', type: 'slide' },
            { x: 1, y: 2, dir: 'west', type: 'slide' },
            { x: 5, y: 1, dir: 'north', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 9 },
        moves: 7,
        walls: [{ x: 0, y: 7 }, { x: 0, y: 8 }],
        dice: [
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 2, y: 1, v: 4, rot: 0 },
            { x: 1, y: 2, v: 4, rot: 0 },
            { x: 2, y: 2, v: 4, rot: 0 },
            { x: 0, y: 0, v: 4, rot: 3 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 0, y: 6, v: 2, rot: 0 },
            { x: 2, y: 6, v: 2, rot: 0 },
            { x: 1, y: 7, v: 2, rot: 0 },
            { x: 3, y: 6, v: 3, rot: 0 },
            { x: 4, y: 6, v: 3, rot: 0 },
            { x: 4, y: 8, v: 3, rot: 0 },
            { x: 3, y: 2, v: 2, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 4, y: 3, v: 2, rot: 0 },
            { x: 4, y: 0, v: 3, rot: 0 },
            { x: 4, y: 2, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 0, v: 1, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'south' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 1, y: 7, dir: 'north', type: 'slide' },
            { x: 4, y: 8, dir: 'north', type: 'slide' },
            { x: 4, y: 3, dir: 'west', type: 'slide' },
            { x: 3, y: 1, dir: 'east', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 8,
        walls: [{ x: 4, y: 4 }, { x: 1, y: 0 }],
        dice: [
            { x: 1, y: 1, v: 2, rot: 0 },
            { x: 2, y: 1, v: 2, rot: 0 },
            { x: 1, y: 2, v: 2, rot: 0 },
            { x: 2, y: 2, v: 2, rot: 0 },
            { x: 0, y: 0, v: 2, rot: 0 },
            { x: 5, y: 2, v: 4, rot: 0 },
            { x: 6, y: 2, v: 4, rot: 0 },
            { x: 6, y: 3, v: 4, rot: 0 },
            { x: 4, y: 1, v: 5, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 6, y: 4, v: 2, rot: 0 },
            { x: 8, y: 4, v: 2, rot: 0 },
            { x: 7, y: 3, v: 2, rot: 0 },
            { x: 8, y: 0, v: 3, rot: 0 },
            { x: 8, y: 2, v: 3, rot: 0 },
            { x: 7, y: 1, v: 3, rot: 0 },
            { x: 3, y: 3, v: 2, rot: 0 },
            { x: 5, y: 3, v: 2, rot: 0 },
            { x: 4, y: 2, v: 2, rot: 0 },
            { x: 3, y: 4, v: 1, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'south' },
            { x: 4, y: 1, dir: 'east' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 1, dir: 'east', type: 'slide' },
            { x: 4, y: 2, dir: 'south', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 9 },
        moves: 7,
        walls: [{ x: 0, y: 0 }, { x: 0, y: 8 }],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 1, y: 0, v: 3, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 0, y: 6, v: 2, rot: 0 },
            { x: 2, y: 6, v: 2, rot: 0 },
            { x: 1, y: 7, v: 2, rot: 0 },
            { x: 3, y: 6, v: 3, rot: 0 },
            { x: 4, y: 6, v: 3, rot: 0 },
            { x: 4, y: 8, v: 3, rot: 0 },
            { x: 3, y: 2, v: 2, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 4, y: 3, v: 2, rot: 0 },
            { x: 3, y: 0, v: 1, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 1, y: 7, dir: 'north', type: 'slide' },
            { x: 4, y: 8, dir: 'north', type: 'slide' },
            { x: 4, y: 3, dir: 'west', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 9,
        walls: [{ x: 4, y: 4 }, { x: 3, y: 0 }],
        dice: [
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 2, y: 1, v: 4, rot: 0 },
            { x: 1, y: 2, v: 4, rot: 0 },
            { x: 2, y: 2, v: 4, rot: 0 },
            { x: 0, y: 0, v: 4, rot: 3 },
            { x: 5, y: 2, v: 5, rot: 0 },
            { x: 6, y: 2, v: 5, rot: 0 },
            { x: 5, y: 3, v: 5, rot: 0 },
            { x: 6, y: 3, v: 5, rot: 0 },
            { x: 4, y: 1, v: 4, rot: 3 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 0, y: 3, v: 3, rot: 0 },
            { x: 6, y: 4, v: 2, rot: 0 },
            { x: 8, y: 4, v: 2, rot: 0 },
            { x: 7, y: 3, v: 2, rot: 0 },
            { x: 8, y: 0, v: 3, rot: 0 },
            { x: 8, y: 2, v: 3, rot: 0 },
            { x: 7, y: 1, v: 3, rot: 0 },
            { x: 2, y: 3, v: 2, rot: 0 },
            { x: 4, y: 3, v: 2, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 4, y: 0, v: 3, rot: 0 },
            { x: 4, y: 2, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'south' },
            { x: 4, y: 1, dir: 'east' },
            { x: 0, y: 3, dir: 'east', type: 'slide' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 1, dir: 'east', type: 'slide' },
            { x: 3, y: 4, dir: 'north', type: 'slide' },
            { x: 3, y: 1, dir: 'east', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 9 },
        moves: 8,
        walls: [{ x: 0, y: 3 }, { x: 0, y: 5 }],
        dice: [
            { x: 1, y: 1, v: 4, rot: 0 },
            { x: 2, y: 1, v: 4, rot: 0 },
            { x: 1, y: 2, v: 4, rot: 0 },
            { x: 2, y: 2, v: 4, rot: 0 },
            { x: 0, y: 0, v: 4, rot: 3 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 0, y: 6, v: 2, rot: 0 },
            { x: 2, y: 6, v: 2, rot: 0 },
            { x: 1, y: 8, v: 2, rot: 0 },
            { x: 3, y: 6, v: 3, rot: 0 },
            { x: 4, y: 6, v: 3, rot: 0 },
            { x: 4, y: 8, v: 3, rot: 0 },
            { x: 3, y: 2, v: 2, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 4, y: 3, v: 2, rot: 0 },
            { x: 4, y: 0, v: 3, rot: 0 },
            { x: 4, y: 2, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 0, v: 1, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'south' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 1, y: 8, dir: 'north', type: 'slide' },
            { x: 1, y: 7, dir: 'north', type: 'slide' },
            { x: 4, y: 8, dir: 'north', type: 'slide' },
            { x: 4, y: 3, dir: 'west', type: 'slide' },
            { x: 3, y: 1, dir: 'east', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 8,
        walls: [{ x: 8, y: 0 }, { x: 8, y: 1 }],
        dice: [
            { x: 2, y: 0, v: 5, rot: 0 },
            { x: 1, y: 1, v: 5, rot: 0 },
            { x: 2, y: 1, v: 5, rot: 0 },
            { x: 3, y: 1, v: 5, rot: 0 },
            { x: 2, y: 2, v: 5, rot: 0 },
            { x: 3, y: 3, v: 5, rot: 0 },
            { x: 6, y: 2, v: 4, rot: 0 },
            { x: 7, y: 2, v: 4, rot: 0 },
            { x: 7, y: 3, v: 4, rot: 0 },
            { x: 5, y: 1, v: 5, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 0, y: 3, v: 3, rot: 0 },
            { x: 5, y: 4, v: 2, rot: 0 },
            { x: 7, y: 4, v: 2, rot: 0 },
            { x: 6, y: 3, v: 2, rot: 0 },
            { x: 3, y: 0, v: 3, rot: 0 },
            { x: 5, y: 0, v: 3, rot: 0 },
            { x: 4, y: 1, v: 3, rot: 0 },
            { x: 2, y: 3, v: 2, rot: 0 },
            { x: 4, y: 3, v: 2, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 8, y: 4, v: 1, rot: 0 }
        ],
        solution: [
            { x: 3, y: 3, dir: 'north' },
            { x: 5, y: 1, dir: 'east' },
            { x: 0, y: 3, dir: 'east', type: 'slide' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 6, y: 3, dir: 'south', type: 'slide' },
            { x: 4, y: 1, dir: 'north', type: 'slide' },
            { x: 3, y: 4, dir: 'north', type: 'slide' }
        ]
    },
    {
        board: { cols: 5, rows: 9 },
        moves: 9,
        walls: [{ x: 0, y: 0 }, { x: 0, y: 8 }],
        dice: [
            { x: 1, y: 1, v: 3, rot: 0 },
            { x: 2, y: 1, v: 3, rot: 0 },
            { x: 3, y: 1, v: 3, rot: 0 },
            { x: 2, y: 2, v: 3, rot: 0 },
            { x: 1, y: 0, v: 3, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 1, y: 3, v: 3, rot: 0 },
            { x: 0, y: 6, v: 2, rot: 0 },
            { x: 2, y: 6, v: 2, rot: 0 },
            { x: 1, y: 8, v: 2, rot: 0 },
            { x: 3, y: 6, v: 3, rot: 0 },
            { x: 4, y: 6, v: 3, rot: 0 },
            { x: 4, y: 8, v: 3, rot: 0 },
            { x: 3, y: 2, v: 2, rot: 0 },
            { x: 3, y: 4, v: 2, rot: 0 },
            { x: 4, y: 3, v: 2, rot: 0 },
            { x: 3, y: 0, v: 1, rot: 0 }
        ],
        solution: [
            { x: 1, y: 0, dir: 'east' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 1, y: 8, dir: 'north', type: 'slide' },
            { x: 1, y: 7, dir: 'north', type: 'slide' },
            { x: 4, y: 8, dir: 'north', type: 'slide' },
            { x: 4, y: 3, dir: 'west', type: 'slide' }
        ]
    },
    {
        board: { cols: 9, rows: 5 },
        moves: 10,
        walls: [{ x: 1, y: 0 }, { x: 8, y: 3 }],
        dice: [
            { x: 1, y: 1, v: 2, rot: 0 },
            { x: 2, y: 1, v: 2, rot: 0 },
            { x: 1, y: 2, v: 2, rot: 0 },
            { x: 2, y: 2, v: 2, rot: 0 },
            { x: 0, y: 0, v: 2, rot: 0 },
            { x: 5, y: 2, v: 4, rot: 0 },
            { x: 6, y: 2, v: 4, rot: 0 },
            { x: 6, y: 3, v: 4, rot: 0 },
            { x: 4, y: 1, v: 5, rot: 0 },
            { x: 0, y: 4, v: 3, rot: 0 },
            { x: 2, y: 4, v: 3, rot: 0 },
            { x: 0, y: 3, v: 3, rot: 0 },
            { x: 6, y: 4, v: 2, rot: 0 },
            { x: 8, y: 4, v: 2, rot: 0 },
            { x: 7, y: 3, v: 2, rot: 0 },
            { x: 8, y: 0, v: 3, rot: 0 },
            { x: 8, y: 2, v: 3, rot: 0 },
            { x: 7, y: 1, v: 3, rot: 0 },
            { x: 3, y: 3, v: 2, rot: 0 },
            { x: 5, y: 3, v: 2, rot: 0 },
            { x: 4, y: 2, v: 2, rot: 0 },
            { x: 3, y: 4, v: 1, rot: 0 }
        ],
        solution: [
            { x: 0, y: 0, dir: 'south' },
            { x: 4, y: 1, dir: 'east' },
            { x: 0, y: 3, dir: 'east', type: 'slide' },
            { x: 1, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 3, dir: 'south', type: 'slide' },
            { x: 7, y: 1, dir: 'east', type: 'slide' },
            { x: 4, y: 2, dir: 'south', type: 'slide' }
        ]
    }
];
